#!/bin/sh

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mio[-1]
	add ucitrack mio
	set ucitrack.@mio[-1].init=mio
	commit ucitrack
EOF
}

rm -rf /tmp/luci-*
exit 0
